version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=minecraft_marketplace
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: gunicorn exchange.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE=postgresql://postgres:postgres@db:5432/minecraft_marketplace
    depends_on:
      db:
        condition: service_healthy

  bot:
    build: .
    command: python manage.py run_bot
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE=postgresql://postgres:postgres@db:5432/minecraft_marketplace
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
