# Generated by Django 4.2.7 on 2025-10-05 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено администратором')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('role', models.CharField(choices=[('CLIENT', 'Клиент'), ('MERCHANT', 'Продавец'), ('ADMIN', 'Администратор')], default='CLIENT', max_length=20, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('merchant_level', models.CharField(blank=True, choices=[('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Золото'), ('PLATINUM', 'Платина')], default='BRONZE', max_length=20, null=True, verbose_name='Уровень продавца')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма продаж')),
                ('total_transactions', models.IntegerField(default=0, verbose_name='Количество сделок')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('experience_points', models.IntegerField(default=0, verbose_name='Опыт')),
                ('approved_items_count', models.IntegerField(default=5, verbose_name='Лимит товаров')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='ID транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Комиссия')),
                ('merchant_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма продавцу')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Ожидает оплаты'), ('PAYMENT_CONFIRMED', 'Оплата подтверждена'), ('ITEM_DELIVERED', 'Товар доставлен'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='PENDING_PAYMENT', max_length=30, verbose_name='Статус')),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплата подтверждена')),
                ('item_delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Товар доставлен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('client_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт клиента')),
                ('merchant_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт продавца')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='bot.telegramuser', verbose_name='Покупатель')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.item', verbose_name='Товар')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='bot.telegramuser', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='bot.telegramuser', verbose_name='Покупатель')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bot.telegramuser', verbose_name='Продавец')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.transaction', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.telegramuser', verbose_name='Продавец'),
        ),
    ]
